jenkins:

# 下面是设定账号密码
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "VMjunbo.1778#$%"
        - id: "dev"
          password: "dev"
  # authorizationStrategy: loggedInUsersCanDoAnything
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Job/Build:dev"
        - "Job/Cancel:dev"
        - "Job/Read:dev"
        - "Job/Workspace:dev"
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
        - "Run/Replay:dev"
        - "Run/Update:dev"

# 下面是从 Gitea 获取登录信息
  # securityRealm:
  #   oic:
  #     allowedTokenExpirationClockSkewSeconds: 0
  #     clientId: "2ac67723-655b-4e83-80b3-84d0ad03ac30"
  #     clientSecret: "{AQAAABAAAABAy2b3+JUbh1w9nhzIJC461ebzxyUBCpl6Q9yj0Q/S2zMN0Fzts5kqepPYRS0CbmUE/yahVVHTvnrS2iocJis4y72YYjyOmIthsymTdOTchQY=}"
  #     disableSslVerification: false
  #     emailFieldName: "email"
  #     escapeHatchSecret: "{AQAAABAAAABAtO+qz5lQ90gDvyJoXYEJpllW0eDZPBY7EIfpqEUO5Qrab6tliK/mYAZu8+wwnCwE/2M7vipGl+yiZAwiYymMts8k6QnaowGXVJBlQ302U4k=}"
  #     fullNameFieldName: "name"
  #     groupIdStrategy: "caseSensitive"
  #     groupsFieldName: "groups"
  #     logoutFromOpenidProvider: false
  #     serverConfiguration:
  #       wellKnown:
  #         wellKnownOpenIDConfigurationUrl: "http://git.xdd.jetmobo.com/.well-known/openid-configuration"
  #     userIdStrategy: "caseSensitive"
  #     userNameField: "name"


  # make sure our jenkins master has 1 executor so that we can run our pipelines
  numExecutors: 1

# specify the seedjob groovy script that will create the  pipelines for us
jobs:
  - file: /usr/local/seedjob.groovy

credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          description: "git account(jenkins)"
          id: "3c24e4e0-7e49-4a56-8cf5-79777e265ab5"
          password: "{AQAAABAAAAAQRK+yoNlglswbWD/kRX5DTqQ3rcjbhX2MkzJq3QzEXro=}"
          scope: GLOBAL
          username: "jenkins"
      